remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Course Material Hub"
author: "Who4u78"

# defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
